name: AvianElements
version: 1.0
api-version: 1.19
authors: [AnonymousBluejay,Soup,Samyed]
website: passerines.dev
main: net.passerines.avians.AvianElements
description: A project
commands:
  itemgive:
    description: gives items
    permission: avian.admin
  aereload:
    description: reloads plugin
    permission: avian.admin
  stats:
    description: shows stats
    permission: avian.user
permissions:
  avian.admin:
    description: da biggest bird
    default: op
  avian.user:
    description: a little birb
    default: true